#!/usr/bin/bash
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from asyncio.subprocess import PIPE
from concurrent.futures import thread
from ctypes import addressof
from typing import Counter
from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
import json
import pexpect
import requests
import copy

import threading


        
counter = 0         

class Ui_Widget(object):
    
    
  
    

    def setupUi(self, Widget):

        Widget.setObjectName("Widget")
        Widget.resize(624, 572)
        self.gridLayout_2 = QtWidgets.QGridLayout(Widget)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabs = QtWidgets.QTabWidget(Widget)
        self.tabs.setObjectName("tabs")
        self.tab_createIface = QtWidgets.QWidget()
        self.tab_createIface.setObjectName("tab_createIface")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_createIface)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_createIface)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 580, 501))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout.setObjectName("gridLayout")
        self.createIface_inputDataSteam = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.createIface_inputDataSteam.setObjectName("createIface_inputDataSteam")
        self.gridLayout.addWidget(self.createIface_inputDataSteam, 5, 1, 1, 1)
        self.createIface_inputPskId = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.createIface_inputPskId.setObjectName("createIface_inputPskId")
        self.gridLayout.addWidget(self.createIface_inputPskId, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 2, 1, 1)
        self.createIface_labelId = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.createIface_labelId.setObjectName("createIface_labelId")
        self.gridLayout.addWidget(self.createIface_labelId, 0, 0, 1, 1)
        self.createIface_inputId = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.createIface_inputId.setObjectName("createIface_inputId")
        self.gridLayout.addWidget(self.createIface_inputId, 0, 1, 1, 1)
        self.createIface_labelPsk = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.createIface_labelPsk.setObjectName("createIface_labelPsk")
        self.gridLayout.addWidget(self.createIface_labelPsk, 4, 0, 1, 1)
        self.createIface_labelDescription = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.createIface_labelDescription.setObjectName("createIface_labelDescription")
        self.gridLayout.addWidget(self.createIface_labelDescription, 1, 0, 1, 1)
        self.createIface_labelPskId = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.createIface_labelPskId.setObjectName("createIface_labelPskId")
        self.gridLayout.addWidget(self.createIface_labelPskId, 3, 0, 1, 1)
        self.createIface_inputDescription = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.createIface_inputDescription.setObjectName("createIface_inputDescription")
        self.gridLayout.addWidget(self.createIface_inputDescription, 1, 1, 1, 1)
        self.createIface_labelDataStreamId = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.createIface_labelDataStreamId.setObjectName("createIface_labelDataStreamId")
        self.gridLayout.addWidget(self.createIface_labelDataStreamId, 5, 0, 1, 1)
        self.createIface_inputPsk = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.createIface_inputPsk.setObjectName("createIface_inputPsk")
        self.gridLayout.addWidget(self.createIface_inputPsk, 4, 1, 1, 1)
        self.createIface_validateButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.createIface_validateButton.setObjectName("createIface_validateButton")
        self.gridLayout.addWidget(self.createIface_validateButton, 6, 0, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_createIface, "")
        self.tab_connectClient = QtWidgets.QWidget()
        self.tab_connectClient.setObjectName("tab_connectClient")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_connectClient)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.connectClient_inputEndPointName = QtWidgets.QLineEdit(self.tab_connectClient)
        self.connectClient_inputEndPointName.setObjectName("connectClient_inputEndPointName")
        self.gridLayout_6.addWidget(self.connectClient_inputEndPointName, 0, 1, 1, 1)
        self.connectClient_validateButton = QtWidgets.QPushButton(self.tab_connectClient)
        self.connectClient_validateButton.setObjectName("connectClient_validateButton")
        self.gridLayout_6.addWidget(self.connectClient_validateButton, 3, 1, 1, 1)
        self.connectClient_inputPsk = QtWidgets.QLineEdit(self.tab_connectClient)
        self.connectClient_inputPsk.setObjectName("connectClient_inputPsk")
        self.gridLayout_6.addWidget(self.connectClient_inputPsk, 2, 1, 1, 1)
        self.connectClient_inputPskId = QtWidgets.QLineEdit(self.tab_connectClient)
        self.connectClient_inputPskId.setObjectName("connectClient_inputPskId")
        self.gridLayout_6.addWidget(self.connectClient_inputPskId, 1, 1, 1, 1)
        self.connectClient_labelEndPointName = QtWidgets.QLabel(self.tab_connectClient)
        self.connectClient_labelEndPointName.setObjectName("connectClient_labelEndPointName")
        self.gridLayout_6.addWidget(self.connectClient_labelEndPointName, 0, 0, 1, 1)
        self.connectClient_labelEndPointName_2 = QtWidgets.QLabel(self.tab_connectClient)
        self.connectClient_labelEndPointName_2.setObjectName("connectClient_labelEndPointName_2")
        self.gridLayout_6.addWidget(self.connectClient_labelEndPointName_2, 1, 0, 1, 1)
        self.connectClient_labelEndPointName_3 = QtWidgets.QLabel(self.tab_connectClient)
        self.connectClient_labelEndPointName_3.setObjectName("connectClient_labelEndPointName_3")
        self.gridLayout_6.addWidget(self.connectClient_labelEndPointName_3, 2, 0, 1, 1)
        self.tabs.addTab(self.tab_connectClient, "")
        self.tab_showResouces = QtWidgets.QWidget()
        self.tab_showResouces.setObjectName("tab_showResouces")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_showResouces)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.showResources_labelid = QtWidgets.QLabel(self.tab_showResouces)
        self.showResources_labelid.setObjectName("showResources_labelid")
        self.gridLayout_7.addWidget(self.showResources_labelid, 0, 0, 1, 1)
        self.showResources_InputId = QtWidgets.QLineEdit(self.tab_showResouces)
        self.showResources_InputId.setObjectName("showResources_InputId")
        self.gridLayout_7.addWidget(self.showResources_InputId, 0, 1, 1, 1)
        self.showResources_display = QtWidgets.QTextBrowser(self.tab_showResouces)
        self.showResources_display.setObjectName("showResources_display")
        self.gridLayout_7.addWidget(self.showResources_display, 1, 1, 1, 1)
        self.showResources_validateButton = QtWidgets.QPushButton(self.tab_showResouces)
        self.showResources_validateButton.setObjectName("showResources_validateButton")
        self.gridLayout_7.addWidget(self.showResources_validateButton, 2, 1, 1, 1)
        self.tabs.addTab(self.tab_showResouces, "")
        self.tab_addResources = QtWidgets.QWidget()
        self.tab_addResources.setObjectName("tab_addResources")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_addResources)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_12 = QtWidgets.QLabel(self.tab_addResources)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)
        self.addResource_inputId = QtWidgets.QLineEdit(self.tab_addResources)
        self.addResource_inputId.setObjectName("addResource_inputId")
        self.gridLayout_8.addWidget(self.addResource_inputId, 0, 1, 1, 1)
        self.addResource_validatioButton = QtWidgets.QPushButton(self.tab_addResources)
        self.addResource_validatioButton.setObjectName("addResource_validatioButton")
        self.gridLayout_8.addWidget(self.addResource_validatioButton, 1, 0, 1, 2)
        self.tabs.addTab(self.tab_addResources, "")
        self.tab_deleteIface = QtWidgets.QWidget()
        self.tab_deleteIface.setObjectName("tab_deleteIface")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_deleteIface)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.deleteInterface_labelId = QtWidgets.QLabel(self.tab_deleteIface)
        self.deleteInterface_labelId.setObjectName("deleteInterface_labelId")
        self.gridLayout_9.addWidget(self.deleteInterface_labelId, 0, 0, 1, 1)
        self.deleteInterface_inputId = QtWidgets.QLineEdit(self.tab_deleteIface)
        self.deleteInterface_inputId.setObjectName("deleteInterface_inputId")
        self.gridLayout_9.addWidget(self.deleteInterface_inputId, 0, 1, 1, 1)
        self.deleteInterface_validateButton = QtWidgets.QPushButton(self.tab_deleteIface)
        self.deleteInterface_validateButton.setObjectName("deleteInterface_validateButton")
        self.gridLayout_9.addWidget(self.deleteInterface_validateButton, 1, 1, 1, 1)
        self.tabs.addTab(self.tab_deleteIface, "")
        self.gridLayout_2.addWidget(self.tabs, 0, 1, 1, 1)

        self.createIface_validateButton.clicked.connect(self.createIface_function)
        self.deleteInterface_validateButton.clicked.connect(self.deleteIface_function)
        self.connectClient_validateButton.clicked.connect(self.connectIface_function)
        self.showResources_validateButton.clicked.connect(self.showResources_function)
        self.addResource_validatioButton.clicked.connect(self.addResoource_function)
        
        
        self.retranslateUi(Widget)
        self.tabs.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Widget)

        

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.createIface_labelId.setText(_translate("Widget", "Id"))
        self.createIface_labelPsk.setText(_translate("Widget", "PSK"))
        self.createIface_labelDescription.setText(_translate("Widget", "Description"))
        self.createIface_labelPskId.setText(_translate("Widget", "PSK Id"))
        self.createIface_labelDataStreamId.setText(_translate("Widget", "Data Stream Id"))
        self.createIface_validateButton.setText(_translate("Widget", "Create"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_createIface), _translate("Widget", "Create interface"))
        self.connectClient_validateButton.setText(_translate("Widget", "Connect"))
        self.connectClient_labelEndPointName.setText(_translate("Widget", "Endpoint "))
        self.connectClient_labelEndPointName_2.setText(_translate("Widget", "PSK Id"))
        self.connectClient_labelEndPointName_3.setText(_translate("Widget", "PSK"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_connectClient), _translate("Widget", "Connect client"))
        self.showResources_labelid.setText(_translate("Widget", "Id"))
        self.showResources_validateButton.setText(_translate("Widget", "Show resources"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_showResouces), _translate("Widget", "Show Resources"))
        self.label_12.setText(_translate("Widget", "Resource Id"))
        self.addResource_validatioButton.setText(_translate("Widget", "Add"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_addResources), _translate("Widget", "Add resources"))
        self.deleteInterface_labelId.setText(_translate("Widget", "IId"))
        self.deleteInterface_validateButton.setText(_translate("Widget", "Delete"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_deleteIface), _translate("Widget", "Delete interface"))

    
    def createIface_function(self):
            
                global ifaceNumber
                url = "https://integ.m2m.orange.com/api/v1/deviceMgt/devices"

                payload = {
                        "id": "urn:lo:nsid:lwm2m:"+ self.createIface_inputId.text(),
                        "name": "Lwm2m device",
                        "description": "device for test",
                        "defaultDataStreamId": "urn:lo:nsid:lwm2m:ifacelwm2m",
                        "interfaces": [
                            {
                                "connector": "lwm2m",
                                "enabled": "true",
                                "definition": {
                                    "endpointName": "balbla",
                                    "security": {
                                        "pskInfo": {
                                            "identity": "pskId",
                                            "secret" : "6d7973656372657470736b617a657274"
                                        }
                                    }
                                }
                            }
                        ]
                    }
                

                #print(type(payload['interfaces'][0]['definition']['endpointName']))
                payload['name'] = self.createIface_inputId.text()
                payload['description'] = self.createIface_inputDescription.text()
                
                payload['interfaces'][0]['definition']['endpointName'] = "urn:lo:lwm2m:"+ self.createIface_inputId.text()
                payload['interfaces'][0]['definition']['security']['pskInfo']['identity'] = self.createIface_inputId.text()
                #payload['interfaces'][0]['definition']['security']['pskInfo']['secret'] = self.pskInput_create.text()

                payload = json.dumps(payload)
                
                #To avoid naming conflicts
                

                headers = {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-API-Key': '1d576207727841a7b9aa2a1f24448f86',
                    'Cookie': 'XSRF-TOKEN=d4af0d8c-5e37-415f-8c72-3da0a7f68c5c'
                }
                response = requests.request("POST", url, headers=headers, data=payload,verify =False)
                print(response.text)
            
    

    def connectIface_function(self):
              
        urn = "java -jar leshan-client-demo.jar "+ "-n "+ "urn:lo:lwm2m:"+ self.connectClient_inputEndPointName.text() +" -i "+ self.connectClient_inputEndPointName.text()+" -p 6d7973656372657470736b617a657274 -u lwm2m.integ.m2m.orange.com"
        urn = urn.strip('"')
        #p = subprocess.Popen(["java","-jar","leshan-client-demo.jar","-n","urn:lo:lwm2m:"+self.connectClient_inputEndPointName.text(),"-i",self.connectClient_inputEndPointName.text(),"-p","6d7973656372657470736b617a657274","-u","lwm2m.integ.m2m.orange.com"], stdin=PIPE,stderr=PIPE)

        #pr = copy.copy(p)
        #p = subprocess.Popen(str(urn),shell = True, stdin=PIPE,stderr=PIPE)
        #p = pexpect.spawn(str(urn))
        p = subprocess.Popen(str(urn),shell = True,stdin=PIPE)
        
        
    
        

    def deleteIface_function(self):
            url = "https://integ.m2m.orange.com/api/v1/deviceMgt/devices/urn:lo:nsid:lwm2m:"+ self.connectClient_inputEndPointName.text()
            payload={}
            headers = {
            'X-API-Key': '1d576207727841a7b9aa2a1f24448f86'
                    }

            response = requests.request("DELETE", url, headers=headers, data=payload,verify =False)

    def showResources_function(self):
        url = "https://integ.m2m.orange.com/api/v1/deviceMgt/devices/urn:lo:nsid:lwm2m:"+self.showResources_InputId.text() +"/twin/supported-objects"
        payload={}
        headers = {
            'X-API-Key': '1d576207727841a7b9aa2a1f24448f86',
            'Cookie': 'XSRF-TOKEN=6247a9f8-7cab-47b4-9706-1df68f174806'
                }

        response = requests.request("GET", url, headers=headers, data=payload,verify = False)

        print(response.text)
        self.showResources_display.setText(response.text)
        

        
    def addResoource_function(self):
        #global counter
        def addResource_thread():
            counter = 0
            print(threading.get_ident())

            urn = "java -jar leshan-client-demo.jar "+ "-n "+ "urn:lo:lwm2m:"+ self.connectClient_inputEndPointName.text() +" -i "+ self.connectClient_inputEndPointName.text()+" -p 6d7973656372657470736b617a657274 -u lwm2m.integ.m2m.orange.com"
            urn = urn.strip('"')
            if(counter==0):
                p = subprocess.Popen(str(urn),shell = True,stdin=PIPE)
                counter = counter = counter+1
                strCreate = "create " + self.addResource_inputId.text() #"create 3424"
                bytesCreate = str.encode(strCreate)
                counter = counter+1
            else:
                strCreate = "create " + self.addResource_inputId.text() #"create 3424"
                bytesCreate = str.encode(strCreate)
            
      
            p.communicate(bytesCreate)
   
        t = threading.Thread(target=addResource_thread)
        t.start()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
